# Generated by Django 4.1.2 on 2022-10-17 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websiteUPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='upi',
            new_name='upiModel',
        ),
    ]
